name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tests (optional)
        # Add your testing commands here

      - name: Build your application
        # Replace with your specific build commands, e.g., dotnet build

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

      - name: Create a deployment archive
        # Replace with your specific archive creation command, e.g., zip -r deployment.zip .

      - name: Deploy to Elastic Beanstalk
        uses: actions/aws-ebextensions@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          application-name: ${{ secrets.ELASTIC_BEANSTALK_APPLICATION_NAME }}
          environment-name: ${{ secrets.ELASTIC_BEANSTALK_ENVIRONMENT_NAME }}
          package: deployment.zip

      - name: Wait for deployment to complete (optional)
        # Add your custom logic to wait for successful deployment

secrets:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ELASTIC_BEANSTALK_APPLICATION_NAME: ${{ secrets.ELASTIC_BEANSTALK_APPLICATION_NAME }}
  ELASTIC_BEANSTALK_ENVIRONMENT_NAME: ${{ secrets.ELASTIC_BEANSTALK_ENVIRONMENT_NAME }}
