name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Install Elastic Beanstalk CLI
      run: |
        sudo apt-get update
        sudo apt-get install python3-pip
        pip3 install --upgrade awsebcli
      # Export the env variables required
      # by the EB CLI
        export AWS_ACCESS_KEY_ID="MY_ACCESS_KEY_ID"
        export AWS_SECRET_ACCESS_KEY="MY_SECRET_ACCESS_KEY"
        export AWS_DEFAULT_REGION="us-east-1"
    - name: Initialize Elastic Beanstalk
      run: eb init -r us-east-1 -p "64bit Amazon Linux 2" test
    - name: Build and Publish
      run: dotnet publish -c Release -o out

    - name: Deploy to AWS Elastic Beanstalk
      run: |
        eb deploy test --region us-east-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
